version: '3.8'
services:
  peario_client:
    build: .
    container_name: peario-client
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped