version: '3.8'
networks:
  traefik-net:
    external: true
services:
  peario-client:
    build: .
    ports:
      - "3000:3000"
    networks:
      - traefik-net
    #environment:
    #  - NODE_ENV=production
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pearioclient.rule=Host(`peario-client.84.8.135.166.sslip.io`)"
      - "traefik.http.services.pearioclient.loadbalancer.server.port=3000"